# Generated by Django 3.0.2 on 2020-01-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerCount', models.IntegerField(blank=True, null=True)),
                ('createDate', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
